In [35]:
import numpy as np
from data import ImageFolderDataset

In [3]:
M = np.identity(3)*3
M_th = np.identity(2)*2
N = np.zeros(np.add(M.shape, M_th.shape ) )
print(N.shape)
N[:M.shape[0], :M.shape[1] ] = M
N[M.shape[0]:, M.shape[1]: ] = M_th
print(N)

(5, 5)
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 2.]]


In [32]:
a = 1/ np.sqrt(2) * np.array([1,1])
b = 1/ np.sqrt(2) * np.array([1,1])

c = np.array([1,0])
d = np.array([0,1])


x = 0.5
test1 = np.array( [np.cos(np.pi/2 *x ), np.sin(np.pi/2 * x)] )
test2 = test1.copy()
test3 = test1 + test2
un_norm = test3 + test2 + test3 
#normed = un_norm / 
print(np.linalg.norm(test1) )

1.0


In [34]:
import torch.nn
import torchvision
import os


torchvision.datasets.MNIST(root = os.path.join( os.path.dirname(os.path.abspath(os.getcwd())), "dataset"), train= True, download = True) 
torchvision.datasets.MNIST(root = os.path.join( os.path.dirname(os.path.abspath(os.getcwd())), "dataset"), train= False, download = True) 

100%|██████████| 9912422/9912422 [00:00<00:00, 28240282.65it/s]


Extracting c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw\train-images-idx3-ubyte.gz to c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw



100%|██████████| 28881/28881 [00:00<00:00, 28739191.89it/s]

Extracting c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw\train-labels-idx1-ubyte.gz to c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw




100%|██████████| 1648877/1648877 [00:00<00:00, 17795521.71it/s]


Extracting c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw\t10k-images-idx3-ubyte.gz to c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw



100%|██████████| 4542/4542 [00:00<?, ?it/s]

Extracting c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw\t10k-labels-idx1-ubyte.gz to c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset\MNIST\raw



Dataset MNIST
    Number of datapoints: 10000
    Root location: c:\Users\Bruker\OneDrive\Dokumenter\TUM\Computational Methods in Many-Body-Physics\dataset
    Split: Test